### ISSUE TITLE
Get into upstream?

### ISSUE THREAD

**Issue by snsmac** [GalliumOS/xkeyboard-config#2]
Hello,
is it possible to get this merged into upstream? This would help people who use chromebooks but do not use GalliumOS

**Comment by rusty122** [comment]
Looks like the changes from upstream are all in [this patch file](https://github.com/GalliumOS/xkeyboard-config/blob/master/debian/patches/chromebook.patch). It could probably use some massaging to make sure that it conforms to the [xkeyboard-config contribution rules](https://www.freedesktop.org/wiki/Software/XKeyboardConfig/Rules).

**Comment by coltondrg** [comment]
Upstream already has Chromebook support, we just add more options and fix things on certain models. Our config also clutters up the menu a bit so I'm pretty sure we would have to restructure things significantly even if they would take it.
